pip uninstall -y azcam
pip uninstall -y azcam-arc
pip uninstall -y azcam-archon
pip uninstall -y azcam-ascom
pip uninstall -y azcam-cryocon
pip uninstall -y azcam-ds9
pip uninstall -y azcam-expstatus
pip uninstall -y azcam-fastapi
pip uninstall -y azcam-focus
pip uninstall -y azcam-imageserver
pip uninstall -y azcam-mag
pip uninstall -y azcam-monitor
pip uninstall -y azcam-observe
pip uninstall -y azcam-scripts
pip uninstall -y azcam-testers
pip uninstall -y azcam-webtools
