[project]
name = "azcam-itl"
version = "22.2.3"
description = "Azcam extension for ITL systems"
license = {file ="LICENSE"}
readme = "README.md"
requires-python = ">=3.9"
keywords=["ccd", "imaging", "astronomy", "sensors"]
authors = [{name="Michael Lesser"},{email = "mlesser@arizona.edu"}]
dependencies = [
    "numpy",
    "ipython",
    "rich",
    "matplotlib",
    "keyring",
    "pyserial",
    "pyvisa",
    "mysql-connector-python",
    "opencv-python-headless",
    "scikit-image",
    "pywin32; sys_platform == 'win32'",
    "azcam",
    "azcam-monitor",
    "azcam-fastapi",
    "azcam-arc",
    "azcam-archon",
    "azcam-ascom",
    "azcam-cryocon",
    "azcam-ds9",
    "azcam-expstatus",
    "azcam-focus",
    "azcam-imageserver",
    "azcam-mag",
    "azcam-observe",
    "azcam-scripts",
    "azcam-testers",
    "azcam-webtools",
]
[project.urls]
Documentation = "https://mplesser.github.io/azcam/"
Repository = "https://github.com/mplesser/azcam-itl/"

[project.scripts]
itl = "azcam_itl.itl:main"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "azcam_itl"