pip install -e ./azcam-90prime
pip install -e ./azcam-bcspec
pip install -e ./azcam-bluechan
pip install -e ./azcam-mont4k
pip install -e ./azcam-vatt4k
pip install -e ./azcam-vattspec
pip install -e ./azcam-lbtguiders
pip install -e ./azcam-soguiders
pip install -e ./azcam-osu4k
pip install -e ./azcam-pepsi
